name: Python CI Workflow with Script Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fission-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Check if dependencies installed correctly
          pip check
          if [ $? -ne 0 ]; then
            echo "Error: Dependency installation failed." >&2
            exit 1
          fi

      - name: Check input files
        id: check-input-files
        run: |
          if [[ ! -f "Fission_ip.txt" ]]; then
            echo "Error: Fission_ip.txt not found." >> $GITHUB_OUTPUT
            exit 1
          fi
          if [[ ! -f "Fission_domain.txt" ]]; then
            echo "Creating empty Fission_domain.txt" >> $GITHUB_OUTPUT
            touch Fission_domain.txt
          else
            echo "Fission_domain.txt exists" >> $GITHUB_OUTPUT
          fi
          
      - name: Run Fission script
        run: |
          python Fission.py
          if [ $? -ne 0 ]; then
            echo "Error: Fission script failed." >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "Fission script executed successfully." >> $GITHUB_OUTPUT

      - name: Upload output files
        uses: actions/upload-artifact@v3
        if: steps.check-input-files.outputs.Error == '' #Only upload if no error
        with:
          name: Fission-output
          paths: Fission_domain.txt, dns_result.txt