name: Python CI Workflow with Script Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fission-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip check  # Verify dependencies

      - name: Check and create Fission_domain.txt
        id: check-input-files
        run: |
          if [[ ! -f "Fission_ip.txt" ]]; then
            echo "::error::Fission_ip.txt not found"
            exit 1
          fi

          if [[ ! -f "Fission_domain.txt" ]]; then
            echo "::set-output::name=create-domain-txt-status-result::true"
            touch Fission_domain.txt
          else
            echo "::set-output::name=create-domain-txt-status-result::false"
          fi

      - name: Run Fission script
        run: python Fission.py

      - name: Upload output files
        uses: actions/upload-artifact@v3
        if: steps.check-input-files.outputs.create-domain-txt-status-result == 'true' || steps.check-input-files.outputs.create-domain-txt-status-result != 'Error' # only upload if script ran successfully
        with:
          name: Fission-output
          paths: Fission_domain.txt, dns_result.txt