name: bestdns

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fission-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # 添加检查依赖是否安装成功的步骤
          pip check  # 检查依赖是否安装正确
          if [ $? -ne 0 ]; then
            echo "Error: Dependency installation failed." >&2
            exit 1
          fi

      - name: Check input files
        id: check-input-files
        run: |
          if [[ ! -f "Fission_ip.txt" ]]; then
            echo "Error: Fission_ip.txt not found. Please include this file in the repository." >> $GITHUB_OUTPUT
            exit 1
          fi
          if [[ ! -f "Fission_domain.txt" ]]; then
            echo "Creating empty Fission_domain.txt"
            touch Fission_domain.txt
            echo "success" >> $GITHUB_OUTPUT  # 标记创建成功
          else
            echo "Fission_domain.txt exists." >> $GITHUB_OUTPUT  # 标记文件存在
          fi

      - name: Run Fission script
        run: |
          python Fission.py
          # 捕捉脚本运行的错误信息
          if [ $? -ne 0 ]; then
            echo "Error: Fission script failed." >&2
            exit 1
          fi
          echo "Fission script executed successfully." >> $GITHUB_OUTPUT

      - name: Upload output files
        uses: actions/upload-artifact@v3
        if: steps.check-input-files.outputs.success == 'success' # 只在检查成功时上传
        with:
          name: Fission-output
          path: Fission_domain.txt
          path: dns_result.txt # 确保上传 dns_result.txt