name: Python CI Workflow with Script Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fission-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip check  # Verify dependencies

      - name: Check and create Fission_domain.txt
        id: create-domain
        run: |
          if [[ ! -f "Fission_ip.txt" ]]; then
            echo "::error::Fission_ip.txt not found"
            exit 1
          fi

          if [[ ! -f "Fission_domain.txt" ]]; then
            touch Fission_domain.txt
            echo "Fission_domain.txt created"
          fi

      - name: Run Fission script
        run: python Fission.py

      - name: 上传 Fission_domain.txt
        uses: actions/upload-artifact@v3
        with:
          name: Fission-output
          path: Fission_domain.txt
          if: steps.create-domain.outcome == 'success'

      - name: 上传 dns_result.txt
        uses: actions/upload-artifact@v3
        with:
          name: Fission-output
          path: dns_result.txt
          if: steps.create-domain.outcome == 'success'