name: Update BestDNS

on:
  repository_dispatch:
    types: [bestdns-update] # 匹配触发事件的名称

jobs:
  update-bestdns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 这里可以添加具体的逻辑，例如解析 IP 并更新 DNS 配置
      - name: Execute BestDNS Logic
        run: |
          echo "BestDNS workflow triggered by ip.yaml"

permissions:
  contents: write  # 允许工作流推送代码

jobs:
  run-fission-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify input files
        run: |
          if [ ! -f "Fission_ip.txt" ]; then
            echo "Error: Fission_ip.txt not found. Please include this file in the repository." >&2
            exit 1
          fi

          if [ ! -f "Fission_domain.txt" ]; then
            echo "Creating empty Fission_domain.txt."
            touch Fission_domain.txt
          fi

      - name: Run Fission script
        id: run-fission-script
        run: python Fission.py

      - name: Commit and push output files
        if: steps.run-fission-script.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 添加并提交更改
          git add Fission_domain.txt
          git commit -m "Update output files from Fission.py execution [skip ci]"
          git push
