name: Update BestDNS

on:
  workflow_dispatch:  # 手动触发
  repository_dispatch:
    types: [bestdns-update]  # 匹配触发事件的名称

permissions:
  contents: write  # 允许工作流推送代码
  id-token: write  # 允许获取 ID Token 用于认证
  actions: read    # 允许工作流读取 actions

jobs:
  update-bestdns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Execute BestDNS Logic
        run: |
          echo "BestDNS workflow triggered by ip.yaml"

      # 以下部分是运行 Fission 脚本
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify input files
        run: |
          if [ ! -f "Fission_ip.txt" ]; then
            echo "Error: Fission_ip.txt not found. Please include this file in the repository." >&2
            exit 1
          fi

          if [ ! -f "Fission_domain.txt" ]; then
            echo "Creating empty Fission_domain.txt."
            touch Fission_domain.txt
          fi

      - name: Run Fission script
        id: run-fission-script
        run: python Fission.py

      - name: Commit and push output files
        if: steps.run-fission-script.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Fission_domain.txt
          git commit -m "Update output files from Fission.py execution [skip ci]"
          git push

      # 删除旧的工作流记录，只保留最近 10 次
      - name: Delete workflow runs
        id: DeleteWorkflowRuns # 给步骤起个ID方便后面引用
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          keep_minimum_runs: 2  # 保留最近的 10 次工作流记录
          baseUrl: https://api.github.com
          repository: dxs1256/Best-DNS # 确保这是你的仓库名
          dry_run: false

      - name: Print Delete Workflow Runs Result
        run: |
          echo "Delete Workflow Runs Conclusion: ${{ steps.DeleteWorkflowRuns.conclusion }}"
          echo "Delete Workflow Runs Output: ${{ steps.DeleteWorkflowRuns.output }}"

      - name: Check Delete Workflow Runs Result
        if: steps.DeleteWorkflowRuns.conclusion == 'failure'
        run: |
          echo "Error deleting workflow runs: ${{ steps.DeleteWorkflowRuns.conclusion }}"
          echo "Error message: ${{ steps.DeleteWorkflowRuns.output }}"
          exit 1 # 终止工作流
