name: Update BestDNS and Delete old workflow runs

on:
  workflow_dispatch:  # 手动触发
  repository_dispatch:
    types: [bestdns-update]  # 匹配触发事件的名称
  schedule:
    - cron: '0 0 1 * *'  # 每月1日00:00执行

permissions:
  contents: write  # 允许工作流推送代码
  id-token: write  # 允许获取 ID Token 用于认证
  actions: read    # 允许工作流读取 actions

jobs:
  update-bestdns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Execute BestDNS Logic
        run: |
          echo "BestDNS workflow triggered by ip.yaml"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify input files
        run: |
          if [ ! -f "Fission_ip.txt" ]; then
            echo "Error: Fission_ip.txt not found. Please include this file in the repository." >&2
            exit 1
          fi

          if [ ! -f "Fission_domain.txt" ]; then
            echo "Creating empty Fission_domain.txt."
            touch Fission_domain.txt
          fi

      - name: Run Fission script
        id: run-fission-script
        run: python Fission.py

      - name: Commit and push output files
        if: steps.run-fission-script.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Fission_domain.txt dns_result.txt
          git commit -m "Update output files from Fission.py execution [skip ci]"
          git push

  delete-old-workflow-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6

      - name: Print Delete Workflow Runs Result
        run: |
          echo "Delete Workflow Runs Conclusion: ${{ steps.DeleteWorkflowRuns.conclusion }}"
          echo "Delete Workflow Runs Output: ${{ steps.DeleteWorkflowRuns.outputs.result }}"

      - name: Check Delete Workflow Runs Result
        if: steps.DeleteWorkflowRuns.conclusion == 'failure'
        run: |
          echo "Error deleting workflow runs: ${{ steps.DeleteWorkflowRuns.conclusion }}"
          echo "Error message: ${{ steps.DeleteWorkflowRuns.outputs.result }}"
          exit 1  # 终止工作流
