name: Python CI Workflow with Script Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fission-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip check  # Verify dependencies

      - name: Check and create Fission_domain.txt
        id: create-domain
        run: |
          if [[ ! -f "Fission_ip.txt" ]]; then
            echo "::error::Fission_ip.txt not found"
            exit 1
          fi

          if [[ ! -f "Fission_domain.txt" ]]; then
            touch Fission_domain.txt
            echo "Fission_domain.txt created"
          fi

      - name: Run Fission script
        run: python Fission.py

      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: Fission-outputs
          # Upload multiple files with a single run
          paths: Fission_domain.txt,dns_result.txt
          if: steps.create-domain.outcome == 'success' && steps.run-fission-script.outcome == 'success'  #Upload only if both create-domain and Run Fission steps succeed.