name: Python CI Workflow with Script Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fission-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip check  # Verify dependencies


      - name: Check and create Fission_domain.txt
        id: create-domain
        run: |
          if [[ ! -f "Fission_ip.txt" ]]; then
            echo "::error::Fission_ip.txt not found" >&2
            exit 1
          fi

          if [[ ! -f "Fission_domain.txt" ]]; then
            touch Fission_domain.txt
            echo "::set-output::name=domain-file-created::true"
          else
            echo "::set-output::name=domain-file-created::false"
          fi
      # No more shell or env, use run directly
      - name: Run Fission script
        id: run-fission
        if: steps.create-domain.outputs.domain-file-created == 'true'
        run: python Fission.py

      - name: Upload Fission_domain.txt
        uses: actions/upload-artifact@v3
        with:
          name: Fission-output-domain
          path: Fission_domain.txt
        if: steps.create-domain.outputs.domain-file-created == 'true'

      - name: Upload dns_result.txt
        uses: actions/upload-artifact@v3
        with:
          name: Fission-output-dns
          path: dns_result.txt
        if: steps.run-fission.outcome == 'success'