name: Get Cloudflare IP Address

on:
  schedule: # 定时运行
    - cron: '0 0 * * *'  # 每天凌晨0点执行
  workflow_dispatch: # 手动触发

jobs:
  get_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install required tools
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # 或你需要的 Python 版本

      - name: Run script
        uses: actions/setup-node@v3
        with:
          node-version: '16' #或你需要的 node 版本
        
      - name: Install npm packages
        run: npm install axios

      - name: Get IP Address using Axios
        id: get-ip
        run: |
          #!/bin/bash
          # 使用Axios请求数据
          curl -s 'https://www.wetest.vip/page/cloudflare/address_v4.html' | jq -r '.html.body.div[2].div[2].div.div[2].div[2].table.tbody.tr[1].td[2]' > Fission_ip.txt
          echo "::set-output name=cloudflareIpFile::Fission_ip.txt"


      - name: Display IP Address (Optional)
        if: steps.get-ip.outputs.cloudflareIpFile
        run: |
          echo "Cloudflare IP Address:"
          cat Fission_ip.txt
        
