name: Update IP Data

on:
  schedule:
    - cron: '0 0 * * *' # 每天定时运行一次（可根据需要调整时间）
  workflow_dispatch: # 手动触发工作流

jobs:
  update-ip-file:
    runs-on: ubuntu-latest

    steps:
    # 1. 检查出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 设置 Python 环境（用于运行脚本）
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml

    # 4. 生成并更新 ip.txt 文件
    - name: Generate and Update ip.txt
      run: |
        # 生成 ip.txt 并获取数据写入
        echo "Fetching data..."
        python - <<EOF
        import requests
        from lxml import html

        # 获取页面内容
        url = "https://www.wetest.vip/page/cloudflare/address_v4.html"
        response = requests.get(url)
        tree = html.fromstring(response.content)

        # 提取指定的 IP 数据
        ip_address = tree.xpath('//*[@id="data-table"]/tbody/tr[1]/td[2]/text()')[0]

        # 写入到 ip.txt 文件
        with open("ip.txt", "w") as file:
            file.write(ip_address.strip())
        EOF
        echo "Data written to ip.txt"

    # 5. 推送更新到仓库
    - name: Push changes to repository
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ip.txt
        git commit -m "Update ip.txt with extracted data"
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD
