name: Update Fission_ip.txt

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨0点运行
  workflow_dispatch:  # 支持手动触发

jobs:
  update-file:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install requests lxml ipaddress

    - name: Fetch and update IP
      run: |
        python -u -c '
          import requests
          from lxml import html
          import ipaddress
          import os

          url = "https://www.wetest.vip/page/cloudflare/address_v4.html"

          try:
              response = requests.get(url, timeout=10)
              response.raise_for_status()  # 检查 HTTP 状态码
              tree = html.fromstring(response.content)
              ip_data = tree.xpath('//*[@id="data-table"]/tbody/tr[1]/td[2]/text()')
              
              if ip_data:
                  ip = ip_data[0].strip()
                  try:
                      ipaddress.ip_address(ip)  # 验证 IP 地址
                      with open("Fission_ip.txt", "w") as f:
                          f.write(ip)
                      print("::set-output name=success::true") # 设置输出
                  except ValueError:
                      print("::error::无效的 IP 地址格式")
              else:
                  print("::error::未找到 IP 地址")
          except requests.exceptions.RequestException as e:
              print(f"::error::请求错误: {e}")
          except Exception as e:
              print(f"::error::其他错误: {e}")
        '

    - name: Commit and Push changes
      if: steps.Fetch-and-update-IP.outputs.success == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Fission_ip.txt
        git commit -m "Update Fission_ip.txt with extracted data"
        git push
