name: Scrape Cloudflare Data and Save to File

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml

    - name: Extract Data and Save to File
      run: |
        python - <<EOF
        import requests
        from lxml import etree

        # 网页地址
        url = "https://www.wetest.vip/page/cloudflare/address_v4.html"
        response = requests.get(url)
        response.raise_for_status()

        # 使用 lxml 解析 HTML
        html = etree.HTML(response.content)
        # 提取目标数据
        data = html.xpath('//*[@id="data-table"]/tbody/tr[1]/td[2]/text()')

        # 保存到文件
        if data:
            with open("ip.txt", "w") as file:
                file.write(data[0].strip())
        else:
            with open("ip.txt", "w") as file:
                file.write("No data found.")
        EOF

    - name: Commit and Push Changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
        git add ip.txt
        git commit -m "Update ip.txt with extracted data"
        git push origin HEAD
