name: Update Fission_ip.txt

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight

jobs:
  update-file:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install requests lxml ipaddress

    - name: Fetch and update IP
      id: fetch-ip
      run: |
        python -u -c '
          import requests
          from lxml import html
          import ipaddress
          import sys

          url = "https://www.wetest.vip/page/cloudflare/address_v4.html"

          try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            tree = html.fromstring(response.content)
            ip_data = tree.xpath("//td[@class='value'][2]/text()")  # Updated XPath

            if ip_data:
              ip = ip_data[0].strip()
              try:
                ipaddress.ip_address(ip)
                with open("Fission_ip.txt", "w") as f:
                  f.write(ip)
                print("::set-output name=success::true")
              except ValueError as e:
                print(f"::error::Invalid IP address format: {ip}")
                sys.exit(1)
            else:
              print("::error::No IP address found.")
              sys.exit(1)

          except requests.exceptions.RequestException as e:
            print(f"::error::Request error: {e}")
            sys.exit(1)
          except Exception as e:
            print(f"::error::An unexpected error occurred: {e}")
            sys.exit(1)
        '

    - name: Commit and Push changes
      if: steps.fetch-ip.outputs.success == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Fission_ip.txt
        git commit -m "Update Fission_ip.txt"
        git push
