name: Get Cloudflare IP Address

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 定时触发

jobs:
  get_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Get IP Address
        id: get-ip
        run: |
          set -euo pipefail

          # Download webpage
          curl -s -f 'https://www.wetest.vip/page/cloudflare/address_v4.html' -o webpage.html

          # Check if the file exists.  Crucial!
          if [[ ! -f webpage.html ]]; then
              echo "Error downloading webpage. Check URL." >&2
              exit 1
          fi

          # Extract IP using xpath
          ip=$(xmlstarlet sel -t -v "//tbody/tr[1]/td[2]/text()" webpage.html)


          # Check if IP was extracted. Crucial!
          if [[ -z "$ip" ]]; then
            echo "Error: Could not extract IP address. Check the webpage structure or the XPath." >&2
            exit 1
          fi

          # Remove whitespace.  Critically important!
          ip="${ip//[[:space:]]/}"

          echo "$ip" > Fission_ip.txt
          echo "::set-output name=cloudflareIp::${ip}"
          echo "::set-output name=cloudflareIpFile::Fission_ip.txt"


      - name: Display IP Address
        if: steps.get_ip.outputs.cloudflareIp
        run: |
          echo "Cloudflare IP Address: ${{ steps.get_ip.outputs.cloudflareIp }}"
          cat Fission_ip.txt
