name: Python CI Workflow with Script Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fission-script:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 检查必要的文件是否存在
      - name: Verify input files
        run: |
          if [ ! -f "Fission_ip.txt" ]; then
            echo "Error: Fission_ip.txt not found. Please include this file in the repository." >&2
            exit 1
          fi
          if [ ! -f "Fission_domain.txt" ]; then
            echo "Creating empty Fission_domain.txt."
            touch Fission_domain.txt

      # 运行 Fission.py 脚本
      - name: Run Fission script
        run: |
          python Fission.py
          echo "Fission script executed successfully."

      # 保存输出文件（可选）
      - name: Upload output files
        uses: actions/upload-artifact@v3
        with:
          name: Fission-output
          path: |
            Fission_domain.txt
            dns_result.txt
